version: "3"
services:
  app:
    build: .
    command: >
      sh -c "python manage.py migrate && make start"
    ports:
      - 8000:8000
    volumes:
      - .:/app
    env_file:
      - ./.env
    depends_on:
      - db

  db:
    image: postgres:15.2-alpine
    environment:
      - POSTGRES_PASSWORD=password
    volumes:
      - /var/lib/postgres
    ports:
      - "5434:5432"